/*
 * Salesforce Commerce Cloud OMS
 * Salesforce Commerce Cloud OMS API test
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CommonApi
 */
@Ignore
public class CommonApiTest {

    private final CommonApi api = new CommonApi();

    /**
     * Server example operation
     *
     * This is an example operation to show how security is applied to the call.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void pingGetTest() throws ApiException {
        api.pingGet();

        // TODO: test validations
    }
}
