/*
 * Salesforce Commerce Cloud OMS
 * Salesforce Commerce Cloud OMS API test
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorModel;
import org.threeten.bp.OffsetDateTime;
import io.swagger.client.model.OrderModel;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrderModuleApi
 */
@Ignore
public class OrderModuleApiTest {

    private final OrderModuleApi api = new OrderModuleApi();

    /**
     * Search order information
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void ommOrdersGetTest() throws ApiException {
        Integer offset = null;
        Integer limit = null;
        OffsetDateTime odf = null;
        OffsetDateTime odt = null;
        Double oaf = null;
        Double oat = null;
        String csp = null;
        String tp1 = null;
        List<OrderModel> response = api.ommOrdersGet(offset, limit, odf, odt, oaf, oat, csp, tp1);

        // TODO: test validations
    }
    /**
     * Detail order information
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void ommOrdersOrderIdGetTest() throws ApiException {
        String orderId = null;
        OrderModel response = api.ommOrdersOrderIdGet(orderId);

        // TODO: test validations
    }
    /**
     * Update order infromation
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void ommOrdersOrderIdPutTest() throws ApiException {
        String orderId = null;
        OrderModel body = null;
        OrderModel response = api.ommOrdersOrderIdPut(orderId, body);

        // TODO: test validations
    }
    /**
     * Update order status
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void ommOrdersOrderIdStatusOrderStatusPatchTest() throws ApiException {
        String orderId = null;
        String orderStatus = null;
        api.ommOrdersOrderIdStatusOrderStatusPatch(orderId, orderStatus);

        // TODO: test validations
    }
    /**
     * Create order information
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void ommOrdersPostTest() throws ApiException {
        OrderModel body = null;
        OrderModel response = api.ommOrdersPost(body);

        // TODO: test validations
    }
}
