/*
 * Salesforce Commerce Cloud OMS
 * Salesforce Commerce Cloud OMS API test
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorModel;
import io.swagger.client.model.ProductModel;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductModuleApi
 */
@Ignore
public class ProductModuleApiTest {

    private final ProductModuleApi api = new ProductModuleApi();

    /**
     * Search product information
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void pmmProductsGetTest() throws ApiException {
        Integer offset = null;
        Integer limit = null;
        List<ProductModel> response = api.pmmProductsGet(offset, limit);

        // TODO: test validations
    }
    /**
     * Check Possible Start Shipment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void pmmProductsPossibleShipmentStartProductIdGetTest() throws ApiException {
        String productId = null;
        Boolean response = api.pmmProductsPossibleShipmentStartProductIdGet(productId);

        // TODO: test validations
    }
    /**
     * Create product information
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void pmmProductsPostTest() throws ApiException {
        ProductModel body = null;
        ProductModel response = api.pmmProductsPost(body);

        // TODO: test validations
    }
    /**
     * Detail product information
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void pmmProductsProductIdGetTest() throws ApiException {
        String productId = null;
        ProductModel response = api.pmmProductsProductIdGet(productId);

        // TODO: test validations
    }
    /**
     * Update product infromation
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void pmmProductsProductIdPutTest() throws ApiException {
        String productId = null;
        ProductModel body = null;
        ProductModel response = api.pmmProductsProductIdPut(productId, body);

        // TODO: test validations
    }
}
