/*
 * Salesforce Commerce Cloud OMS
 * Salesforce Commerce Cloud OMS API test
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * 注文情報
 */
@Schema(description = "注文情報")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-11-12T08:45:31.599Z[GMT]")
public class OrderModel {
  @SerializedName("orderId")
  private String orderId = null;

  @SerializedName("customerId")
  private String customerId = null;

  @SerializedName("orderStatus")
  private String orderStatus = null;

  @SerializedName("shipmentStatus")
  private String shipmentStatus = null;

  @SerializedName("paymentStatus")
  private String paymentStatus = null;

  @SerializedName("paymentAmount")
  private Double paymentAmount = null;

  @SerializedName("orderAmount")
  private Double orderAmount = null;

  @SerializedName("shipFee")
  private Double shipFee = null;

  @SerializedName("orderDate")
  private OffsetDateTime orderDate = null;

  public OrderModel orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * 注文ID(Key)
   * @return orderId
  **/
  @Schema(description = "注文ID(Key)")
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public OrderModel customerId(String customerId) {
    this.customerId = customerId;
    return this;
  }

   /**
   * 注文者ID
   * @return customerId
  **/
  @Schema(description = "注文者ID")
  public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  public OrderModel orderStatus(String orderStatus) {
    this.orderStatus = orderStatus;
    return this;
  }

   /**
   * 注文状態コード
   * @return orderStatus
  **/
  @Schema(description = "注文状態コード")
  public String getOrderStatus() {
    return orderStatus;
  }

  public void setOrderStatus(String orderStatus) {
    this.orderStatus = orderStatus;
  }

  public OrderModel shipmentStatus(String shipmentStatus) {
    this.shipmentStatus = shipmentStatus;
    return this;
  }

   /**
   * 出荷状態コード
   * @return shipmentStatus
  **/
  @Schema(description = "出荷状態コード")
  public String getShipmentStatus() {
    return shipmentStatus;
  }

  public void setShipmentStatus(String shipmentStatus) {
    this.shipmentStatus = shipmentStatus;
  }

  public OrderModel paymentStatus(String paymentStatus) {
    this.paymentStatus = paymentStatus;
    return this;
  }

   /**
   * 決済状態コード
   * @return paymentStatus
  **/
  @Schema(description = "決済状態コード")
  public String getPaymentStatus() {
    return paymentStatus;
  }

  public void setPaymentStatus(String paymentStatus) {
    this.paymentStatus = paymentStatus;
  }

  public OrderModel paymentAmount(Double paymentAmount) {
    this.paymentAmount = paymentAmount;
    return this;
  }

   /**
   * 決済金額
   * @return paymentAmount
  **/
  @Schema(description = "決済金額")
  public Double getPaymentAmount() {
    return paymentAmount;
  }

  public void setPaymentAmount(Double paymentAmount) {
    this.paymentAmount = paymentAmount;
  }

  public OrderModel orderAmount(Double orderAmount) {
    this.orderAmount = orderAmount;
    return this;
  }

   /**
   * 注文金額
   * @return orderAmount
  **/
  @Schema(description = "注文金額")
  public Double getOrderAmount() {
    return orderAmount;
  }

  public void setOrderAmount(Double orderAmount) {
    this.orderAmount = orderAmount;
  }

  public OrderModel shipFee(Double shipFee) {
    this.shipFee = shipFee;
    return this;
  }

   /**
   * 配送料
   * @return shipFee
  **/
  @Schema(description = "配送料")
  public Double getShipFee() {
    return shipFee;
  }

  public void setShipFee(Double shipFee) {
    this.shipFee = shipFee;
  }

  public OrderModel orderDate(OffsetDateTime orderDate) {
    this.orderDate = orderDate;
    return this;
  }

   /**
   * 注文日時
   * @return orderDate
  **/
  @Schema(description = "注文日時")
  public OffsetDateTime getOrderDate() {
    return orderDate;
  }

  public void setOrderDate(OffsetDateTime orderDate) {
    this.orderDate = orderDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderModel orderModel = (OrderModel) o;
    return Objects.equals(this.orderId, orderModel.orderId) &&
        Objects.equals(this.customerId, orderModel.customerId) &&
        Objects.equals(this.orderStatus, orderModel.orderStatus) &&
        Objects.equals(this.shipmentStatus, orderModel.shipmentStatus) &&
        Objects.equals(this.paymentStatus, orderModel.paymentStatus) &&
        Objects.equals(this.paymentAmount, orderModel.paymentAmount) &&
        Objects.equals(this.orderAmount, orderModel.orderAmount) &&
        Objects.equals(this.shipFee, orderModel.shipFee) &&
        Objects.equals(this.orderDate, orderModel.orderDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderId, customerId, orderStatus, shipmentStatus, paymentStatus, paymentAmount, orderAmount, shipFee, orderDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderModel {\n");
    
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    orderStatus: ").append(toIndentedString(orderStatus)).append("\n");
    sb.append("    shipmentStatus: ").append(toIndentedString(shipmentStatus)).append("\n");
    sb.append("    paymentStatus: ").append(toIndentedString(paymentStatus)).append("\n");
    sb.append("    paymentAmount: ").append(toIndentedString(paymentAmount)).append("\n");
    sb.append("    orderAmount: ").append(toIndentedString(orderAmount)).append("\n");
    sb.append("    shipFee: ").append(toIndentedString(shipFee)).append("\n");
    sb.append("    orderDate: ").append(toIndentedString(orderDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
